name: Run Deploy
inputs:
  HEROKU_AUTH_TOKEN:
    required: true
    description: HEROKU AUTH TOKEN

runs:
  using: composite
  steps:
    - name: deploy
      shell: sh
      run: |
        sudo apt-get update -qy
        sudo apt-get install -y ruby-dev
        sudo gem install dpl
        sudo dpl --provider=heroku --app=marmitex --api-key=${{ inputs.HEROKU_AUTH_TOKEN }}
