name: Run tests
inputs:
  SECRET_KEY:
    required: true
    description: Secret Key Django

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup env
      shell: bash
      run: |
        cp .env-sample .env

    - name: Setup dependencies
      shell: bash
      run: |
        pip install --upgrade pip && pip install -r requirements.txt
    - name: Run tests
      shell: bash
      env:
        SECRET_KEY: ${{ inputs.SECRET_KEY }}
      run: |
        coverage run /app/source/manage.py test
        coverage report -m
