# Generated by Django 4.1 on 2022-08-21 17:33

from __future__ import absolute_import

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("company", "0001_create_table_company_and_company_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="PacketLunch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_added",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data de inserção"
                    ),
                ),
                (
                    "protein_name",
                    models.CharField(max_length=120, verbose_name="Nome da proteina"),
                ),
                ("description", models.TextField(verbose_name="Descrição")),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Valor"
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="inserido por",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.company",
                        verbose_name="Companhia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Marmita",
                "verbose_name_plural": "Marmitas",
            },
        ),
        migrations.CreateModel(
            name="MenuDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_added",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data de inserção"
                    ),
                ),
                (
                    "day_week",
                    models.CharField(
                        choices=[
                            ("sun", "Domingo"),
                            ("mon", "Segunda"),
                            ("tue", "Terça"),
                            ("wed", "Quarta"),
                            ("thu", "Quinta"),
                            ("fri", "Sexta"),
                            ("sat", "Sábado"),
                        ],
                        max_length=4,
                        verbose_name="Dia da semana",
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="inserido por",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.company",
                        verbose_name="Companhia",
                    ),
                ),
                (
                    "packet_lunch",
                    models.ManyToManyField(
                        to="menu.packetlunch", verbose_name="Marmita"
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu do dia",
                "verbose_name_plural": "Menu do dia",
            },
        ),
    ]
